unqualified-search-registries = ['docker.io', 'quay.io']

[[registry]]
prefix = 'docker.io'
location = 'docker.io'

[[registry.mirror]]
location = 'atomhub.openatom.cn'

[[registry.mirror]]
location = 'docker.m.daocloud.io'

[[registry.mirror]]
location = 'hub.rat.dev'
