[main]
dpi-aware = auto
exit-on-keyboard-focus-loss = no
font = monospace:size=13 #@reference_tag(font)
match-mode = fzf
#icon-theme = #@reference_tag(icon_theme)
icons-enabled = no
inner-pad = 4
lines = 20
layer = overlay
prompt = '> '
show-actions = no
terminal = 'foot --' #@reference_tag(terminal)
width = 45

[border]
width = 1
radius = 0

[colors] #@reference_tag(color)
background = 1a1b26ff
border = b16286ff
match = fe8019ff
text = ebdbb2ff
prompt = 586e75ff
input = ebdbb2ff
selection = ebdbb2ff
selection-match = fe8019ff
selection-text = 282828ff

[dmenu]
mode = text
exit-immediately-if-empty = no

[key-bindings]
cancel = Escape
execute = Return KP_Enter
execute-or-next = Tab

# vim:ft=confini:
