
target-colorspace-hint=no

# Filter
af=@repan:!pan="stereo|FL=FR|FR=FL" # 输入 $ 可将左右声道互换

# 驱动 & 编码
ao=pipewire,pulse,jack,alsa
hwdec=no
gpu-context=waylandvk,wayland,x11vk,x11,displayvk,drm
#profile=vqueue
vd-lavc-fast=yes
vo=gpu-next

# 缓存
cache-on-disk=no
cache-pause=yes
cache-pause-wait=5

# 终端信息
msg-level=ffmpeg/demuxer=error,sub/ass=fatal
msg-module=yes

# 音频播放
audio-display=no
volume-max=250
replaygain=track

# 播放列表
playlist-start=auto

# 字幕
embeddedfonts=no
sub-auto=fuzzy
sub-hinting=native
sub-file-paths=../sub
sub-font=monospace #@reference_tag(font)
#sub-gray=yes

# 截图
screenshot-format=png
screenshot-dir=~~/shot
# screenshot-png-compression=9

[vqueue]
ad-lavc-threads=0
vd-lavc-threads=0
vd-queue-enable=yes
vd-queue-max-bytes=1GiB
vd-queue-max-samples=512
vd-queue-max-secs=10
