allow-overwrite=true
always-resume=false
async-dns=false
auto-file-renaming=true
bt-enable-lpd=true
bt-max-peers=120
connect-timeout=10
console-log-level=warn
continue=true
daemon=false
disk-cache=64M
dry-run=false
enable-color=true
file-allocation=none
follow-torrent=false
human-readable=true
log-level=notice
max-connection-per-server=5
max-file-not-found=2
max-tries=2
min-split-size=20M
quiet=false
rpc-allow-origin-all=true
rpc-listen-all=true
#@reference_tag(aria2_rpc)
rpc-secret=5040
stderr=true
summary-interval=60

# vim:ft=conf:
