set -gs editor "${EDITOR}"
set -as terminal-features ',foot*:RGB:Tc,alacritty*:RGB:Tc'
#set -as terminal-overrides ',foot*:RGB:Tc,alacritty*:RGB:Tc'

set -g extended-keys on
set -g extended-keys-format csi-u
set -g default-command "${SHELL}"
set -g history-limit 4096
set -g mode-keys vi
set -g mouse on

#@reference_tag(color)
set -g message-style 'fg=#7aa2f7,bg=#3b4261'
set -g message-command-style 'fg=#7aa2f7,bg=#3b4261'
set -g status 'on'
set -g status-left '[#S]'
set -g status-right '%Y-%m-%d %H:%M:%S'
set -g status-justify 'left'
set -g status-style 'fg=#7aa2f7,bg=#16161e'

set -gw mode-style 'fg=#7aa2f7,bg=#3b4261'
set -gw pane-border-style 'fg=#3b4261'
set -gw pane-active-border-style 'fg=#7aa2f7'
set -gw window-status-current-format '[#F#I:#W]'
set -gw window-status-format '[#F#I:#W]'
set -gw window-status-current-style 'underscore'

unbind -a
set -g prefix C-b
bind l source-file ~/.config/tmux/tmux.conf
bind p copy-mode
bind w select-pane -U
bind a select-pane -L
bind s select-pane -D
bind d select-pane -R
bind q previous-window
bind e next-window
bind b new-window -c '#{pane_current_path}'
bind z detach-client
bind n split-window -v -c '#{pane_current_path}'
bind m split-window -h -c '#{pane_current_path}'
