[main]
app-id = foot
bold-text-in-bright = yes
dpi-aware = no
font = monospace:size=14 #@reference_tag(font)
locked-title = yes
login-shell = no
#resize-delay-ms = 100
shell = /bin/tmux
title = Foot

[colors-dark] #@reference_tag(color)
background = 1a1b26
foreground = aaffaa
# Black
bright0 = 282828
regular0 = 1a1b26
# Red
bright1 = ff0000
regular1 = cd0000
# Green
bright2 = 00ff00
regular2 = 00cd00
# Yellow
bright3 = ffff00
regular3 = cdcd00
# Blue
bright4 = 0044ff
regular4 = 0022cd
# Magenta
bright5 = ff00ff
regular5 = cd00cd
# Cyan
bright6 = 00ffff
regular6 = 00cdcd
# White
regular7 = e5e5e5
bright7 = ffffff

[csd]
preferred = server

[cursor]
style = block
unfocused-style = none
blink = no
#underline-thickness = 2px

[mouse]
hide-when-typing = yes

[scrollback]
#indicator-format = percentage
indicator-position = none
lines = 1024
multiplier = 5.0

# vim:ft=confini:
