bind = SUPER, grave, exec, hyprctl reload
bind = SUPER, z, killactive
bind = SUPER, w, cyclenext
bind = SUPER&SHIFT, w, cyclenext, prev
bind = SUPER, s, workspace, +1
bind = SUPER&SHIFT, s, workspace, -1
bind = SUPER, d, movetoworkspace, +1
bind = SUPER&SHIFT, d, movetoworkspace, -1
bind = SUPER, q, fullscreen, 1
bind = SUPER&CTRL, q, fullscreen, 0
bind = SUPER, a, togglefloating
bind = SUPER&CTRL, a, pin
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
bindm = SUPER&CTRL, mouse:273, resizewindow 1
bind = SUPER&CTRL, Return, exec, foot bash
bind = SUPER&ALT, Return, exec, tmux-attach.sh
bind = SUPER, l, exec, loginctl lock-session
bind = SUPER, r, exec, fuzzel
bind = , XF86AudioLowerVolume, exec, volctl.py -5
bind = , XF86AudioRaiseVolume, exec, volctl.py +5
bind = , XF86AudioMute, exec, volctl.py mute
bind = SUPER, Print, exec, shot.sh
bind = SUPER&CTRL, Print, exec, shot.sh slurp
bind = , XF86Cut, exec, shot.sh
bind = CTRL, XF86Cut, exec, shot.sh slurp
bind = SUPER, k, exec, passmenu.sh gui type
bind = SUPER&CTRL, k, exec, passmenu.sh gui
