general {
    lock_cmd = pidof waylock || waylock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispath dpms on
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
