source = deco.conf
source = behav.conf
source = input.conf
source = render.conf
source = bind.conf
bind = SUPER&ALT, Z, exit
bind = SUPER, Return, exec, foot
animations {
    enabled = false
}
misc {
    force_default_wallpaper = 0
}
exec-once = wayinit.sh
exec-shutdown = wayterm.sh
